#!/bin/bash

# Ensure Assignment 4 and wrapper are compiled
make a4 wrapper

# Reusable function to run tests and construct exactly the requested Markdown tables
run_algorithm_tests() {
    local assignment=$1
    local algo=$2
    local prefix=$3
    
    local output_dir="${assignment}/outputs"
    mkdir -p "$output_dir"
    
    local output_file="${output_dir}/${algo}_results.md"
    
    # Initialize the Markdown table with the exact headers specified in the PDF
    echo "### ${algo^^} Results" > "$output_file"
    echo "" >> "$output_file"
    
    if [ "$algo" == "kmeans" ]; then
        # K-Means Header[cite: 8]
        echo "| File | N | D | K | Max Iter. | Actual Iter. | WCSS | Time | Status |" >> "$output_file"
        echo "|---|---|---|---|---|---|---|---|---|" >> "$output_file"
    elif [ "$algo" == "fastmap" ]; then
        # FastMap Header[cite: 8]
        echo "| File | N | Target k | Pivots (per dim) | Avg. Distance Error | Time | Status |" >> "$output_file"
        echo "|---|---|---|---|---|---|---|---|" >> "$output_file"
    fi
    
    # Loop through test files and append the generated rows
    for file in $(ls testFiles/${prefix}*.txt | sort); do
        if [ -f "$file" ]; then
            echo "Running $file..."
            # Capture only the last line (the markdown row) generated by the driver
            ./wrapper "$assignment" "$algo" "$file" | tail -n 1 >> "$output_file"
        fi
    done
    
    echo "Saved $algo table to $output_file!"
}

echo "Starting test suite for Assignment 4..."

run_algorithm_tests "assignment_04" "kmeans" "km_"
run_algorithm_tests "assignment_04" "fastmap" "fm_"

echo "Assignment 4 tests finished successfully! Check your outputs folder."